default: &default
  adapter: <%= Rails.application.credentials.dig(:database, :adapter) %>
  encoding: <%= Rails.application.credentials.dig(:database, :encoding) %>
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  socket: <%= Rails.application.credentials.dig(:database, :socket) %>

development:
  <<: *default
  database: salary_management_api_ror_development

test:
  <<: *default
  database: salary_management_api_ror_test

production:
  primary: &primary_production
    <<: *default
    database: salary_management_api_ror_production
    username: salary_management_api_ror
    password: <%= ENV["SALARY_MANAGEMENT_API_ROR_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: salary_management_api_ror_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: salary_management_api_ror_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: salary_management_api_ror_production_cable
    migrations_paths: db/cable_migrate
